import { useFormContext, useWatch } from 'react-hook-form'
import {
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import {
  BREAK_DURATION_UNIT_OPTIONS,
  BREAK_PAY_TYPE_OPTIONS,
  BREAK_TYPE_OPTIONS,
} from '../data/data'
import {
  getRuleSpanMinutes,
  type BreakType,
  type ShiftPolicyFormValues,
} from '../data/schema'
import { buildBreakTypeFields, formatMinutes } from '../utils'
import { Time24Input } from './time-24-input'

type BreakTimeRuleFieldsProps = {
  index: number
}

// Empty input reads as undefined.
function toNumberOrUndefined(value: string, asNumber: number) {
  return value === '' ? undefined : asNumber
}

export function BreakTimeRuleFields({ index }: BreakTimeRuleFieldsProps) {
  const form = useFormContext<ShiftPolicyFormValues>()
  const rule = useWatch({ control: form.control, name: `rules.${index}` })
  if (!rule || rule.policy_type !== 'break_time') return null

  // Resets every other type's fields.
  const changeBreakType = (next: BreakType) => {
    const fields = buildBreakTypeFields(next)
    for (const [key, value] of Object.entries(fields)) {
      form.setValue(
        `rules.${index}.${key as keyof typeof fields}`,
        value as never,
        { shouldDirty: true }
      )
    }
    form.clearErrors(`rules.${index}`)
  }

  const rangeMinutes =
    rule.break_type === 'range'
      ? getRuleSpanMinutes(rule.from_time ?? '', rule.to_time ?? '')
      : 0

  return (
    <>
      <FormField
        control={form.control}
        name={`rules.${index}.pay_type`}
        render={({ field }) => (
          <FormItem className='space-y-2'>
            <FormControl>
              <RadioGroup
                value={field.value}
                onValueChange={(value) => {
                  if (!value) return
                  field.onChange(value)
                }}
                className='flex gap-4'
              >
                {BREAK_PAY_TYPE_OPTIONS.map((option) => (
                  <Label
                    key={option.value}
                    className='flex cursor-pointer items-center gap-1.5 font-normal'
                  >
                    <RadioGroupItem value={option.value} />
                    {option.label}
                  </Label>
                ))}
              </RadioGroup>
            </FormControl>
            <FormMessage />
          </FormItem>
        )}
      />

      <FormField
        control={form.control}
        name={`rules.${index}.break_type`}
        render={({ field }) => (
          <FormItem>
            <FormLabel className='text-xs'>Break Time Type</FormLabel>
            <Select
              value={field.value}
              onValueChange={(value) => {
                // See `radix-select-bubble-select-wipes-programmatic-value`.
                if (!value || value === field.value) return
                changeBreakType(value as BreakType)
              }}
            >
              <FormControl>
                <SelectTrigger className='h-8 w-full'>
                  <SelectValue placeholder='Select a break type' />
                </SelectTrigger>
              </FormControl>
              <SelectContent>
                {BREAK_TYPE_OPTIONS.map((option) => (
                  <SelectItem key={option.value} value={option.value}>
                    {option.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            <FormMessage />
          </FormItem>
        )}
      />

      {rule.break_type === 'fixed' && <FixedDurationFields index={index} />}

      {rule.break_type === 'manual' && (
        <p className='rounded-md bg-muted px-3 py-2 text-sm text-muted-foreground'>
          Logged in by punch — when the employee clocks the break through
          Clock-time or the App.
        </p>
      )}

      {rule.break_type === 'dynamic' && (
        <FormField
          control={form.control}
          name={`rules.${index}.threshold_hours`}
          render={({ field }) => (
            <FormItem>
              <FormLabel className='text-xs'>
                Generated by system, after threshold of
              </FormLabel>
              <div className='flex items-center gap-2'>
                <FormControl>
                  <Input
                    type='number'
                    min={0.5}
                    max={24}
                    step={0.5}
                    className='h-8 w-28'
                    value={field.value ?? ''}
                    onChange={(e) =>
                      field.onChange(
                        toNumberOrUndefined(
                          e.target.value,
                          e.target.valueAsNumber
                        )
                      )
                    }
                  />
                </FormControl>
                <span className='text-sm text-muted-foreground'>hours</span>
              </div>
              <FormMessage />
            </FormItem>
          )}
        />
      )}

      {rule.break_type === 'range' && (
        <div className='flex items-start gap-2'>
          <FormField
            control={form.control}
            name={`rules.${index}.from_time`}
            render={({ field }) => (
              <FormItem className='flex-1'>
                <FormLabel className='text-xs'>From</FormLabel>
                <FormControl>
                  <Time24Input
                    className='h-8'
                    value={field.value ?? ''}
                    onChange={field.onChange}
                    onBlur={field.onBlur}
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />
          <FormField
            control={form.control}
            name={`rules.${index}.to_time`}
            render={({ field }) => (
              <FormItem className='flex-1'>
                <FormLabel className='text-xs'>To</FormLabel>
                <FormControl>
                  <Time24Input
                    className='h-8'
                    value={field.value ?? ''}
                    onChange={field.onChange}
                    onBlur={field.onBlur}
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />
          {/* Derived from the window — read-only. */}
          <div className='flex-1 space-y-2'>
            <Label className='text-xs'>Duration</Label>
            <Input
              disabled
              readOnly
              className='h-8'
              value={rangeMinutes > 0 ? formatMinutes(rangeMinutes) : '—'}
            />
          </div>
        </div>
      )}
    </>
  )
}

// Stored as total minutes; the unit only changes how it's typed in.
function FixedDurationFields({ index }: { index: number }) {
  const form = useFormContext<ShiftPolicyFormValues>()
  const rule = useWatch({ control: form.control, name: `rules.${index}` })
  if (!rule || rule.policy_type !== 'break_time') return null

  const unit = rule.duration_unit ?? 'minutes'
  const total = rule.duration_minutes

  return (
    <div className='space-y-2'>
      <div className='flex flex-wrap items-center gap-4'>
        <Label className='text-xs'>Duration</Label>
        <RadioGroup
          value={unit}
          onValueChange={(value) => {
            if (!value) return
            form.setValue(
              `rules.${index}.duration_unit`,
              value as typeof unit,
              { shouldDirty: true }
            )
          }}
          className='flex gap-4'
        >
          {BREAK_DURATION_UNIT_OPTIONS.map((option) => (
            <Label
              key={option.value}
              className='flex cursor-pointer items-center gap-1.5 font-normal'
            >
              <RadioGroupItem value={option.value} />
              {option.label}
            </Label>
          ))}
        </RadioGroup>
      </div>

      <FormField
        control={form.control}
        name={`rules.${index}.duration_minutes`}
        render={({ field }) => (
          <FormItem>
            {unit === 'minutes' ? (
              <div className='flex items-center gap-2'>
                <FormControl>
                  <Input
                    type='number'
                    min={1}
                    step={1}
                    className='h-8 w-28'
                    aria-label='Duration in minutes'
                    value={field.value ?? ''}
                    onChange={(e) =>
                      field.onChange(
                        toNumberOrUndefined(
                          e.target.value,
                          e.target.valueAsNumber
                        )
                      )
                    }
                  />
                </FormControl>
                <span className='text-sm text-muted-foreground'>min</span>
              </div>
            ) : (
              <div className='flex items-center gap-2'>
                <FormControl>
                  <Input
                    type='number'
                    min={0}
                    max={24}
                    step={1}
                    className='h-8 w-20'
                    aria-label='Duration hours'
                    value={total == null ? '' : Math.floor(total / 60)}
                    onChange={(e) => {
                      const hours =
                        e.target.value === '' ? 0 : e.target.valueAsNumber
                      const minutes = (total ?? 0) % 60
                      field.onChange(hours * 60 + minutes || undefined)
                    }}
                  />
                </FormControl>
                <span className='text-sm text-muted-foreground'>h</span>
                <Input
                  type='number'
                  min={0}
                  max={59}
                  step={1}
                  className='h-8 w-20'
                  aria-label='Duration minutes'
                  value={total == null ? '' : total % 60}
                  onChange={(e) => {
                    const minutes =
                      e.target.value === '' ? 0 : e.target.valueAsNumber
                    const hours = Math.floor((total ?? 0) / 60)
                    field.onChange(hours * 60 + minutes || undefined)
                  }}
                />
                <span className='text-sm text-muted-foreground'>m</span>
              </div>
            )}
            <FormMessage />
          </FormItem>
        )}
      />
    </div>
  )
}
